name: Node.js Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Bun Env
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install
        run: bun install

      - name: Lint
        run: bun run lint
        continue-on-error: true

      - name: Format
        run: bun run format

      - name: Commit All Changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        id: auto-commit-action
        with:
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          commit_message: '[ci] Format changes'
          push: ${{ steps.auto-commit-action.outputs.changes_detected }}
