name: Node.js Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun Env
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install
        run: bun install

      - name: Lint
        run: bun run lint
        continue-on-error: true

      - name: Format
        run: bun run format

      - name: Set GIt Config
        run: |
          git config --global user.name "devmirza-bot"
          git config --global user.email "mirzazaid4740@gmail.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m '[ci] format'
          git push
