name: Node.js Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun Env
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install Turbo
        run: bun add turbo

      - name: Install
        run: bun install

      - name: Bulld Lint & CheckTypes
        run: turbo build lint check-types
